# Generated by Django 4.1.13 on 2024-11-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.BigIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('speciality', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.BigIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_no', models.IntegerField()),
                ('time_range', models.CharField(max_length=50)),
                ('max_patient', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.doctor')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('cancel', 'Canceled'), ('appointed', 'Appointed'), ('rejected', 'Rejected')], max_length=10)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.doctor')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.patient')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.slot')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.doctor')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareApp.slot')),
            ],
        ),
    ]
