# Generated by Django 4.1.13 on 2024-11-07 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
