# Generated by Django 4.1.13 on 2024-11-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareApp', '0004_doctor_password_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='time_range',
            field=models.CharField(max_length=255),
        ),
    ]
